# Generated by Django 2.2.10 on 2020-05-27 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='userid',
            field=models.IntegerField(blank=True, null=True, verbose_name='номер пользователя '),
        ),
        migrations.AlterField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Option'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='текст ответа'),
        ),
        migrations.AlterField(
            model_name='multioption',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='descr',
            field=models.CharField(max_length=200, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='start_date',
            field=models.DateTimeField(verbose_name='дата старта'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
    ]
